paths:
  .github/workflows/*.yml:
    ignore:
      # actionlint does not support the `$/` self-repository syntax yet
      # issue: https://github.com/rhysd/actionlint/issues/711
      # PR: https://github.com/rhysd/actionlint/pull/732
      - 'specifying action "\$/.+" in invalid format because ref is missing.'
